### ISSUE TITLE
[feature] Use correct loan term labels (days not months)

### ISSUE THREAD

**Issue by helpfulBro** [ETHLend/Baiji-public#10]
![image](https://user-images.githubusercontent.com/25915621/48479882-570a7480-e854-11e8-8079-ad3d1e4fd40f.png)

See above - this should also align with notifications as not all months are 30 days.

**Comment by The-3D** [comment]
agree with this one, will be implemented

**Comment by The-3D** [comment]
this has been implemented and a release candidate will be made available soon
