### ISSUE TITLE
[feature] Include a notification icon / list for loan events/notifcations

### ISSUE THREAD

**Issue by helpfulBro** [ETHLend/Baiji-public#13]
Since not all users read their emails, it would be very helpful to also have a notifications icon/panel similar to Radar Relay.

You could show,

- Upcoming installment dates
- Loans close to collateral call
- Links to competitions
- Announcements of new collateral tokens
- All the same notifications that would be sent via email or SMS

![image](https://user-images.githubusercontent.com/25915621/48877509-4c9d3b80-ee4f-11e8-8904-88d487163ce1.png)

**Comment by The-3D** [comment]
yes we discussed about this internally, will be implemented but not in this next release, we will update afterwards
