### ISSUE TITLE
[bug] When creating a loan, clicking the down arrow does not focus on the next field

### ISSUE THREAD

**Issue by helpfulBro** [ETHLend/Baiji-public#17]
- If I click on the down arrow after entering an amount, the currency section is still opaque.
- If I click the arrow a second time it is displayed correctly.
- If I hit enter, it is displayed correctly.

![image](https://user-images.githubusercontent.com/25915621/48878453-2bd6e500-ee53-11e8-917e-bf678518926d.png)

**Comment by The-3D** [comment]
this has been fixed in our internal version. will notify when the release candidate is ready
