### ISSUE TITLE
[feature] Show the token and amount being transfered

### ISSUE THREAD

**Issue by helpfulBro** [ETHLend/Baiji-public#19]
This request is to fund a loan with LEND - however the panel only shows ETH so doesn't accurately represent the transaction about to take place.

Suggestions,

1. Replace instances of ETH in balance, amount to be sent, and total with actual token to be sent.

![image](https://user-images.githubusercontent.com/25915621/48879443-72c6d980-ee57-11e8-80dc-bdef90f41484.png)

**Comment by The-3D** [comment]
this has been implemented in the release candidate, will be available soon
