### ISSUE TITLE
[Bug] Can't sign-up 

### ISSUE THREAD

**Issue by Kant19** [ETHLend/Baiji-public#20]
Hi, 

I just can't sign up on https://baijitest.ethlend.io/signup. 
When I click "Submit", I have a message "loading" and after nothing happen. 

I'm using Windows10 and my browser is Google Chrome, it says that "there is no security conexion". 

![lend](https://user-images.githubusercontent.com/38186288/49329201-d483f380-f57b-11e8-8524-dd7cde82a30b.png)

Thanks in advance.

**Comment by The-3D** [comment]
There is aconnection issue from the baiji application to the backend at the moment, we are checking the issue

**Comment by The-3D** [comment]
closed as we redeployed the whole infrastructure
