### ISSUE TITLE
0.4.0 - Design 'Unlock Wallet' view

### ISSUE THREAD

**Issue by YarrrPirate** [ETHLend/Baiji-public#21]
The 'eye' needs to be centered and the 'import wallet' as well. (remove the 'reset' icon inside of the 'import wallet' button.

<img width="680" alt="screen shot 2018-12-14 at 11 52 40 am" src="https://user-images.githubusercontent.com/38859999/49999310-c6c86800-ff96-11e8-836d-0a8df5b14702.png">

**Comment by eboadom** [comment]
@YarrrPirate the eye vertically centered you mean, no?

**Comment by YarrrPirate** [comment]
Yes, vertical for the eye and horizontal for 'import wallet'
