### ISSUE TITLE
design feature request. macbook 13´ adation needed

### ISSUE THREAD

**Issue by swinxx** [ETHLend/Baiji-public#3]
to deliver best user experience possible -> 
<img width="640" alt="screensize" src="https://user-images.githubusercontent.com/8355835/46571111-66ea8b00-c96f-11e8-9821-82b9254a53ef.png">
on a 13 inch macbook pro some screens should be adopted

**Comment by ernesto-usal** [comment]
This will be fixed during the period on tesnet.

**Comment by The-3D** [comment]
the home panel has been completely revamped and this issue is not present anymore. Also the whole theme as been reworked to better adapt to screens with very high res and high zoom ratios
