### ISSUE TITLE
This is not a valid loan or the data returned is invalid. Please contact our support service for more information  notification

### ISSUE THREAD

**Issue by 9only9** [ETHLend/Baiji-public#36]
I made this loan request - https://kovan.etherscan.io/address/0xB1E36eDcc26251266A46bAeb832212A47F297A22

It appeared to go through fine and after clicking on a green notification box in the bottom right the following notification appeared.

![screenshot](https://user-images.githubusercontent.com/44017060/50041650-d01e0700-0060-11e9-8f92-a47e65dc0e2d.png)

when i go to loans section i see this 

![screenshot 1](https://user-images.githubusercontent.com/44017060/50041654-d9a76f00-0060-11e9-964b-49a40c62f7af.png)

2nd attempt it worked fine 

cheers

**Comment by sirsoth** [comment]
Its possible as also devs are testing at some specific moments there are shortage of service, in that moment its possible this happen, if you achieve to replicate this problem let us know to check that

**Comment by 9only9** [comment]
This loan I made https://kovan.etherscan.io/address/0x8F8a3e72A990bAd8D1716baA05Dd1B116f8e8c4d  went through fine with all the normal notifications but it shows up in my "My borrowed Loans" the same as the above mentioned

![screenshot 3](https://user-images.githubusercontent.com/44017060/50052597-12157e80-012f-11e9-8c35-f90b0a5768d1.png)

**Comment by The-3D** [comment]
this might indicate a shortage in the oraclize service. Unfortunately the oraclize service in testnet has some unpredictable behavior that thankfully does not appear in production. We will reset the oraclize service and verify if that is the source of the problem.

**Comment by The-3D** [comment]
we replaced our development oraclize bridge in the current baiji testnet with the official kovan oraclize that is working as expected. closing this
