### ISSUE TITLE
loan that is "waiting for collateral" not displayed in My loans section after funding  

### ISSUE THREAD

**Issue by 9only9** [ETHLend/Baiji-public#39]
I funded this loan - https://kovan.etherscan.io/address/0x1b3f017AE06C5AC357EC6F5D23004d0d6afbe1Eb 

It appears as waiting for collateral in the below screenshot  

![screenshot 1](https://user-images.githubusercontent.com/44017060/50042488-2775a480-006c-11e9-8b39-1bc8f840b3b9.png)

but does not show up in the "my funded loans" section at all 

![screenshot](https://user-images.githubusercontent.com/44017060/50042508-6e639a00-006c-11e9-9a11-f7791cbbf4c0.png)

**Comment by eboadom** [comment]
@9only9 during some maintenances we did during the weekend, we had some inconsistencies with the BTC loans. Will be fixed soon.

**Comment by The-3D** [comment]
this is now fixed and apart from temporary shortages of the bitcoin oracle because of us doing maintanance/upgrades, should not happen anymore. Closing this
