### ISSUE TITLE
Can't add collateral for a loan request. 

### ISSUE THREAD

**Issue by 9only9** [ETHLend/Baiji-public#4]
I've not been able to add collateral on two loan requests.  I've tried it a few times over the last few days but cannot get beyond the below screen shoot. 

![screenshot](https://user-images.githubusercontent.com/44017060/46717874-06f72b80-cc72-11e8-880f-df09cde4adec.png)

On a separate note, the above screen is a little confusing as every time you land on the page you have to click on the "refresh the price" button to move on.  It may be better to have the refresh the price option called validate collateral or complete transaction. 

Cheers

**Comment by ernesto-usal** [comment]
@9only9 In what kind of loan are you trying to place the collateral in terms of loan currency and collateral?

**Comment by 9only9** [comment]
I'm requesting a loan of 111.95 ETHUSD and using 1 ETH as collateral   
this is contract https://kovan.etherscan.io/address/0xF2a56fB48CEBA8c59e9f6A5b4745Cd918A1433EB

**Comment by 9only9** [comment]
I've just been trying to fund some new ETH loan requests. Some of them have worked but for others the transaction does not go through as they get stuck on the above screen shot or the below window appears  and then it gets stuck after i submit  

![screenshot](https://user-images.githubusercontent.com/44017060/46863137-3c8d4780-ce1f-11e8-9984-efad21afda0c.png)
 
This is strange because the quantity of ETH on the confirm transaction window  is not the same as the loan i was trying to fund.

A side note - When the transactions are successful transactions a  notification comes up in the bottom right corner and it is quite difficult to see as it is quite small and a similar color to the back drop.

**Comment by The-3D** [comment]
we fixed the issue with funding the loans, also the color of the notifications has been changed to improve visibility

**Comment by sirsoth** [comment]
Hello @9only9 could you please share with me the ETH address where you want to receive the LEND tokens for your reward? 
I suggest you a personal wallet and not an exchange/third party one.

**Comment by 9only9** [comment]
Hi Pablo

Thank you - this is a private metamask account -
0xE16090c7Cf3B2908c7cbB9833d30A0e473d3Db78

Best,

Paul
