### ISSUE TITLE
Hover over explanations for loan status in the my loans section  

### ISSUE THREAD

**Issue by 9only9** [ETHLend/Baiji-public#44]
I think it would be helpful to new users if there were hover explanations for some of the loan status in the my loans sections that clarify exactly what the status means. for example after taking the below loan i see the below notification 

![screenshot](https://user-images.githubusercontent.com/44017060/50210807-c1e12b00-037f-11e9-890e-b805372fe548.png)

and I go to my loans section and see the status is "validating offer" but i have no idea what that means and when i will receive the loan  

![screenshot 1](https://user-images.githubusercontent.com/44017060/50210384-9f024700-037e-11e9-83e7-1f1f3a0cc650.png)

**Comment by The-3D** [comment]
"validating offer" is the state in which the borrower has taken the loan, and there is a oraclize call in between to validate the collateral price. It should last a couple of minutes, after that it should correctly go to waitingForPayback. If it didn't happen, it means that you took the offer while we were having problem with kovan oraclize last week.
Noted as  enanhcement.

**Comment by helpfulBrother** [comment]
I was about the report the same thing, the design needs tweaking to allow a user to find out easily what each status means, expected time-frame for completion for validating offer status.

Hover tool tips for desktop would work well.
Mobile might need a different approach.
