### ISSUE TITLE
[feature] Include the worth borrowed/lent in USD

### ISSUE THREAD

**Issue by guybrushT54** [ETHLend/Baiji-public#45]
Hi Team,

It could be fine to improve UX by adding the worth borrowed or lent in USD.
see screenshot.

<img width="1502" alt="screenshot 2018-12-20 at 18 50 53" src="https://user-images.githubusercontent.com/38115816/50302064-479ccd80-0489-11e9-8bb5-d0a5910217ba.png">
<img width="1515" alt="screenshot 2018-12-20 at 18 51 09" src="https://user-images.githubusercontent.com/38115816/50302074-4e2b4500-0489-11e9-82cb-bbd29dadca30.png">

Tks,
Valentin

**Comment by The-3D** [comment]
noted, thanks for the suggestion. We will add this, if not for this release for a subsequent patch.
