### ISSUE TITLE
Copy to Clipboard of seeds not work

### ISSUE THREAD

**Issue by Eranthea** [ETHLend/Baiji-public#47]
When you try to create new wallet and come out the seed phrase, the button COPY TO CLIPBORAD do not work. So seeds is not copy to clipborad

**Comment by The-3D** [comment]
@Eranthea  can you please specify which browser/operating system are you using? We are not able to replicate right now. In any case, clipboard copy is a potentially unsafe operation so it will be removed in the actual release. The button will only be used as a confirmation that the user has copied the seed phrase somewhere.
