### ISSUE TITLE
Impossible to lend

### ISSUE THREAD

**Issue by Eranthea** [ETHLend/Baiji-public#48]
I try to lend a loan and when i click on FUND THIS LOAD and then confirm th transaction on follow screen come out this message in righ down corner on page
Oops! Something happened
Error: Returned error: Insufficient funds. The account you tried to send transaction from does not have enough funds. Required 152700000000000000 and got: 0.

and there is no call to matamask
On metamask im in Kovan testnet and i have 3eth and the loan to lend was 0.15

**Comment by The-3D** [comment]
The application is not using metamask anymore, but the integrated inapp wallet. Thus the funds need to be transferred to the inapp wallet first. So the application was correctly saying "insufficients funds", as most likely your wallet ETH balance was at 0. This is for the first baiji release, with future upgrades we will give the user the possibility to switch between the inapp wallet and other external wallets/ledgers. I'm closing this
