### ISSUE TITLE
Bug Found "Withdraw Repayments"

### ISSUE THREAD

**Issue by swinxx** [ETHLend/Baiji-public#5]
After pressing "Withdraw Repayments" and after "Submit Transaction" a red window appears on the right (see attachement) - seems like something is not working. 

<img width="394" alt="lend_bug_001" src="https://user-images.githubusercontent.com/8355835/47266169-1e1c0000-d533-11e8-94f8-41ec73ccb23c.png">
<img width="413" alt="lend_bug_001_2" src="https://user-images.githubusercontent.com/8355835/47266170-1e1c0000-d533-11e8-8d86-36ee88ff6498.png">
<img width="528" alt="lend_bug_001_3" src="https://user-images.githubusercontent.com/8355835/47266171-1eb49680-d533-11e8-9c59-a93bc9777b30.png">

**Comment by The-3D** [comment]
will check on this thanks

**Comment by The-3D** [comment]
this has been fixed in the release candidate, will be made available soon

**Comment by sirsoth** [comment]
Hello @swinxx  could you please share with me the ETH address where you want to receive the LEND tokens for your reward? 
I suggest you a personal wallet and not an exchange/third party one.

**Comment by morrishanson** [comment]
Am Fr., 26. Apr. 2019 um 14:20 Uhr schrieb Pablo Candela <
notifications@github.com>:

**Comment by morrishanson** [comment]
how much do i get :)


Am Fr., 26. Apr. 2019 um 14:24 Uhr schrie
