### ISSUE TITLE
[feature] After generating seed words, the user should be prompted to re-enter before continuing.

### ISSUE THREAD

**Issue by helpfulBrother** [ETHLend/Baiji-public#52]
This design / flow of re-entering the seed words, or at least selecting them in the right order seems to be the common design practice now.

This will ensure users have actually saved their seed words somewhere before continuing.

**Comment by The-3D** [comment]
this is a controversial one, as while it's true that it gives more confidence to us that the user has written down the seeds, it makes the onboarding procedure more complicated by adding one more (annoying) step. And in any case we are not sure that the user will take care of the seeds, as we cannot be sure that he doesn't inadvertently throw the seed phrase in the trash bin immediately after. We are going to change anyway the "Copy to clipboard" button to a more secure confirmation button that the user has written down the seed phrase, as copying to clipboard is potentially unsafe. Thanks for the feedback anyway

**Comment by helpfulBrother** [comment]
Fair enough.

Perhaps some advice to save the seed on physical paper and as a note within BitWarden / LastPass (but not on Google Drive, or Dropbox)?
