### ISSUE TITLE
[bug] Loan stuck in 'validating offer' stage, TX out of gas.

### ISSUE THREAD

**Issue by helpfulBrother** [ETHLend/Baiji-public#54]
Attempted to fund a loan, no sitting in 'validating offer' state. TX out of gas.

![image](https://user-images.githubusercontent.com/44999712/50634304-e6e9b680-0f99-11e9-93a6-4a2fe89d846c.png)

Contract : https://kovan.etherscan.io/address/0x21E7a0C0B220a09cbB07932152ebFA33e39dc878#internaltx

**Comment by The-3D** [comment]
thanks for  finding this. This happens only in the case of ERC20 as loan currency (DAI in this case) as the transfer of ERC20 is more expensive in terms of gas compared to eth transfers. @sirsoth  this is a confirmed bug, please keep track of it for the bug bounty
