### ISSUE TITLE
[bug] How do I deposit LEND into my wallet?

### ISSUE THREAD

**Issue by helpfulBrother** [ETHLend/Baiji-public#57]
I know that if I send LEND to my ETH address it will be credited, but how would a new user know this as there are only links to exchanges.
![image](https://user-images.githubusercontent.com/44999712/50672211-720e8f00-1022-11e9-9c83-118ec3b589f2.png)

The LEND token needs the some functions as ETH,BTC and ERC20 tokens. Mock-up below.
![image](https://user-images.githubusercontent.com/44999712/50672342-388a5380-1023-11e9-8f8c-27851b4cb87e.png)

**Comment by The-3D** [comment]
We have actually implemented this already, the code is about to be reviewed and we are going to release a new testnet version with the new features/bugfixes
