### ISSUE TITLE
[feature/bug] Why is the minimum amount not populated?

### ISSUE THREAD

**Issue by helpfulBrother** [ETHLend/Baiji-public#59]
A couple of things here,

a) There is enough space to use full words, considering changing Max., Min., Tot. to Maximum, Minimum and Total respectively? As a general rule, avoiding abbreviation unless absolutely required is a good idea.

b) Why is the minimum amount not populated? If it cannot be changed the Min and Max should have the same value?

![image](https://user-images.githubusercontent.com/44999712/50672589-da5e7000-1024-11e9-9800-592195837c21.png)

**Comment by The-3D** [comment]
We will remove the abbreviations. The minimum is not populated as the  creator of the offer decided to not allow a minimum amount to be chosen (as you can see there is no slider to choose the loan amount). We can either keep this or hide the minimum amount in the overview

**Comment by helpfulBrother** [comment]
Okay that makes sense, but again is not obvious for someone who is new.

Perhaps where the loan is a set amount,

a) hide Min amount
b) rename the Max amount label -> Amount

Then it's clear the loan is only for a single amount.
