### ISSUE TITLE
[bug] liquidation price not displayed for over collateralised loans

### ISSUE THREAD

**Issue by helpfulBrother** [ETHLend/Baiji-public#6]
![image](https://user-images.githubusercontent.com/44999712/48406213-a03cc480-e77f-11e8-82b1-6fe8cd4589fb.png)

Might have to change the design to allow the price ot overflow into the green, or have the liquidation price below the red square when it's not visibile in the bar? 

Just some ideas - people will want to know the liquidation price.

**Comment by The-3D** [comment]
Actually the design has an hover handler that should display the price with a tooltip. This is an extreme case (probably no one will ever take a loan so much overcollateralized) but it might happen if the price of the collateral raises a lot compared to the loan currency. Will investigate on this.
