### ISSUE TITLE
[bug] Loan not displayed in 'My Loans' after funding.

### ISSUE THREAD

**Issue by helpfulBrother** [ETHLend/Baiji-public#8]
![image](https://user-images.githubusercontent.com/44999712/48406438-3375fa00-e780-11e8-9890-cfe1d50a4006.png)

TX : https://kovan.etherscan.io/tx/0xe9fb524c5a18a62f4e1313fdd87f1be8d073c9eab006f31c6a5b85983d3bc455

**Comment by The-3D** [comment]
will check on this, thanks
